[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=64", "setuptools_scm>=8"]

[dependency-groups]
codeflash = [
    "codeflash>=0.7",  # Pin to keep recent
    "lcaw[dev]",
]
dev = ["lcaw[dev]"]

[project]
authors = [
    {email = "hello@futurehouse.org", name = "FutureHouse technical staff"},
]
# Full list: https://pypi.python.org/pypi?%3Aaction=list_classifiers
classifiers = [
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python",
]
dependencies = [
    "coredis",
    "fhaviary>=0.8.2",  # For core namespace
    "limits",
    "pydantic~=2.0,>=2.10.1,<2.10.2",
    "tiktoken>=0.4.0",
    "typing-extensions; python_version <= '3.11'",  # for typing.override
    'litellm; python_version < "3.13"',
    'litellm>=1.49.1; python_version >= "3.13"',  # For removal of imghdr
]
description = "A client to provide LLM responses."
dynamic = ["version"]
license = {file = "LICENSE"}
name = "lcaw"
readme = "README.md"
requires-python = ">=3.11"

[project.optional-dependencies]
dev = [
    "fhaviary[xml]",
    "ipython>=8",  # Pin to keep recent
    "lcaw[local]",
    "mypy>=1.8",  # Pin for mutable-override
    "pre-commit>=3.4",  # Pin to keep recent
    "pylint-pydantic",
    "pytest-asyncio",
    "pytest-mock",
    "pytest-recording",
    "pytest-rerunfailures",
    "pytest-subtests",
    "pytest-sugar",
    "pytest-timer[colorama]",
    "pytest-xdist",
    "pytest>=8",  # Pin to keep recent
    "python-dotenv",
    "refurb>=2",  # Pin to keep recent
]
local = [
    "numpy",
    "sentence-transformers",
]

[tool.ruff]
extend = "../../pyproject.toml"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools_scm]
root = "../.."
version_file = "src/lcaw/version.py"
